-- 20 T-Series Films titles (see README "T-Series catalog"). Metadata only: the full films are NOT
-- included. poster_url points at the TMDB image CDN (local SVG fallback is /api/posters/<id>.svg);
-- trailer_youtube_id is the official trailer on the T-Series YouTube channel (embedded, not hosted).
-- video_path is a short Blender open-movie sample clip (CC BY 3.0) used as the prototype preview (ids 7–20 reuse the six clips).
-- Prices in paise (14900 = ₹149). rating = TMDB user score out of 10 (checked 2026-10-08).
INSERT INTO movies (title, description, poster_url, video_path, duration_min, price_cents, currency, genre, rating, year, trailer_youtube_id, tmdb_id) VALUES
('Aashiqui 2', 'A fading rock star with a drinking problem discovers a bar singer in Goa and helps her become a star, while his own career and health fall apart.', 'https://image.tmdb.org/t/p/w500/z18DWXBRxn3kz00sIVhC7ZK39Qm.jpg', 'videos/big-buck-bunny.mp4', 134, 9900, 'INR', 'Drama · Romance', 6.8, 2013, 'FyXXgpPqe6w', 192558),
('Kabir Singh', 'A brilliant but volatile surgeon spirals into self-destruction after the woman he loves is married off to someone else.', 'https://image.tmdb.org/t/p/w500/iHPF4rt8HTuDZzNH1L2FCiPzN48.jpg', 'videos/elephants-dream.mp4', 172, 12900, 'INR', 'Drama · Romance', 6.4, 2019, 'RiANSSgCuJk', 577328),
('Animal', 'A son''s obsessive need for his industrialist father''s love turns into a violent crusade after an attempt on his father''s life.', 'https://image.tmdb.org/t/p/w500/hr9rjR3J0xBBKmlJ4n3gHId9ccx.jpg', 'videos/tears-of-steel.mp4', 204, 19900, 'INR', 'Action · Crime · Drama', 6.1, 2023, '8FkLRUJj-o0', 781732),
('Tanhaji: The Unsung Warrior', 'Maratha commander Tanaji Malusare leads a daring night assault to recapture the Kondhana fort for Chhatrapati Shivaji Maharaj.', 'https://image.tmdb.org/t/p/w500/fZhgcUVwV7ocglL5XDq4ygsfXqD.jpg', 'videos/sintel-snow.mp4', 135, 12900, 'INR', 'Action · Drama · History', 6.4, 2020, 'cffAGIYTEHU', 584850),
('Bhool Bhulaiyaa 2', 'A carefree drifter poses as a psychic to help a young woman hide from her family, and ends up in a haveli haunted by the spirit Manjulika.', 'https://image.tmdb.org/t/p/w500/fw0oMHiMt9qOuKEJEmzFiCNAnXc.jpg', 'videos/sintel-trailer.mp4', 145, 14900, 'INR', 'Horror · Comedy', 6.1, 2022, 'P2KRKxAb2ek', 695962),
('Drishyam 2', 'Seven years after the case was closed, a new police chief reopens the investigation into Vijay Salgaonkar and his family.', 'https://image.tmdb.org/t/p/w500/wk8Vu0DI0MiNLaXXiVqAwjLRKL5.jpg', 'videos/elephants-dream-2.mp4', 142, 14900, 'INR', 'Thriller · Drama · Mystery', 8.0, 2022, 'cxA2y9Tgl7o', 1029827),
('De De Pyaar De', 'A 50-year-old divorced investment banker in London falls for a woman half his age, then has to introduce her to the ex-wife and grown children he left behind in India.', 'https://image.tmdb.org/t/p/w500/lKxbegRPahPDeOYeaDHhsNJDZU8.jpg', 'videos/big-buck-bunny.mp4', 135, 9900, 'INR', 'Romance · Comedy', 6.1, 2019, 'EJUD2PptXrk', 590401),
('Sonu Ke Titu Ki Sweety', 'Sonu is sure his lifelong best friend Titu''s too-perfect fiancee Sweety is trouble, and the two start a battle of wits to win Titu over before the wedding.', 'https://image.tmdb.org/t/p/w500/1nsVHEVKOag8syzGtqnlYlbMQdh.jpg', 'videos/elephants-dream.mp4', 138, 7900, 'INR', 'Comedy · Romance', 6.6, 2018, 'M2q64UowX9g', 498598),
('Tu Jhoothi Main Makkaar', 'A man who earns a living helping couples break up falls in love himself, then discovers that his new fiancee wants out of their relationship.', 'https://image.tmdb.org/t/p/w500/zHLtNP4KP0GMi6p1ACf2QvVnBvI.jpg', 'videos/tears-of-steel.mp4', 164, 14900, 'INR', 'Romance · Comedy · Family', 6.3, 2023, 'Cx_Dtwn4ayw', 611359),
('Satyameva Jayate', 'A vigilante sets corrupt Mumbai policemen on fire one by one, while an honest senior officer races to catch him before he strikes again.', 'https://image.tmdb.org/t/p/w500/yXdzw7Mg7UeAnIRMsMgP9DiiGuk.jpg', 'videos/sintel-snow.mp4', 140, 9900, 'INR', 'Action · Thriller', 6.4, 2018, 'odXKXLG43co', 531597),
('Bhool Bhulaiyaa 3', 'Fake exorcist Rooh Baba is hired by a royal family to deal with the ghost of Manjulika, but the palace seems to hold more than one Manjulika.', 'https://image.tmdb.org/t/p/w500/3AfHD1HoaQpQwKH8kxRdBKVmzeU.jpg', 'videos/sintel-trailer.mp4', 158, 19900, 'INR', 'Horror · Comedy', 5.4, 2024, '6YMY62tMLUA', 980599),
('Malang', 'Years after a carefree romance in Goa ends in tragedy, a man returns to the island on a killing spree, pursued by two very different policemen.', 'https://image.tmdb.org/t/p/w500/2COzaii4BnT1O6bbXfAxtoTmADm.jpg', 'videos/elephants-dream-2.mp4', 135, 12900, 'INR', 'Romance · Action · Thriller', 7.0, 2020, 'sft5baUuzQs', 661043),
('Saaho', 'An undercover cop infiltrates a crime syndicate fighting over a dead don''s empire, chasing a stolen black box worth billions across Mumbai and the desert city of Waaji.', 'https://image.tmdb.org/t/p/w500/rWXIpR2uPkwb1Hrhjj2FA62FGdu.jpg', 'videos/big-buck-bunny.mp4', 170, 14900, 'INR', 'Action · Adventure · Thriller', 5.7, 2019, 'lD0-ztCFydA', 454292),
('Marjaavaan', 'A gangster''s loyal enforcer gives up violence for a mute Kashmiri girl, setting him on a collision course with his boss''s vengeful son.', 'https://image.tmdb.org/t/p/w500/xILMQFZMQdJq3D7J6TuLrW6A3W5.jpg', 'videos/elephants-dream.mp4', 135, 9900, 'INR', 'Romance · Action', 6.9, 2019, 'L7TbPUOn1hc', 627715),
('Pati Patni Aur Woh', 'A small-town government engineer, bored three years into his marriage, invents a sob story to win over a glamorous new colleague, until his wife catches on.', 'https://image.tmdb.org/t/p/w500/9sAegdBnkfucqhrsocR47zCKcez.jpg', 'videos/tears-of-steel.mp4', 126, 9900, 'INR', 'Comedy · Romance', 6.1, 2019, 'L7a1JSeqaXk', 590350),
('Shubh Mangal Zyada Saavdhan', 'Kartik and Aman are in love and determined to marry, but first they have to win over Aman''s conservative family in Allahabad.', 'https://image.tmdb.org/t/p/w500/il9y4odx9el9Imwz6VMQrz9BcNz.jpg', 'videos/sintel-snow.mp4', 117, 7900, 'INR', 'Comedy · Romance', 6.0, 2020, 'r6r8UYU7Zcs', 606535),
('Arjun Patiala', 'A newly posted Punjab cop and his bumbling sidekick set out to clean up their district''s crime, while a pushy crime reporter keeps getting in the way, and under his skin.', 'https://image.tmdb.org/t/p/w500/nuPerJWV04xQMQUu9J6K6H4iFCB.jpg', 'videos/sintel-trailer.mp4', 106, 7900, 'INR', 'Comedy · Romance', 4.1, 2019, 'nR7ETMS7Eo0', 531601),
('Shehzada', 'Raised in a Delhi chawl by a scheming father, Bantu learns he was swapped at birth with a billionaire''s son and talks his way into the rich family that is really his.', 'https://image.tmdb.org/t/p/w500/zyAHBSGEhiQMtE822NFkNKapMYi.jpg', 'videos/elephants-dream-2.mp4', 145, 12900, 'INR', 'Drama · Comedy · Action', 5.5, 2023, 'vbSGPIS2_ao', 884434),
('Ek Villain Returns', 'A masked serial killer is preying on young women in Mumbai, and a cab driver, a hot-headed rich heir and a pop star are all pulled into the hunt for him.', 'https://image.tmdb.org/t/p/w500/4BqMeSSPaC7spmj4Zl7htiigCkV.jpg', 'videos/big-buck-bunny.mp4', 128, 12900, 'INR', 'Action · Crime · Thriller', 6.0, 2022, 'swPhyd0g6K8', 682401),
('Batla House', 'A Delhi Police officer defends his team against a storm of public suspicion after a deadly encounter with suspected terrorists in a Jamia Nagar flat.', 'https://image.tmdb.org/t/p/w500/lHATvvxVvcHRy9G8ZJGXA7J6JEg.jpg', 'videos/elephants-dream.mp4', 146, 9900, 'INR', 'Action · Drama · Thriller', 6.8, 2019, 'dG3K6jB3iW8', 550485);
